### ISSUE TITLE
Debian Wheezy

### ISSUE THREAD

**Issue by CustomIRCd** [TwinUsers/debian-pi-netinst#2]
When installing wheezy, i've noticed it uses 1.5gb of space. Jessie however uses only 400mb 

possibly a bug?

**Comment by TwinUsers** [comment]
hello @CustomIRCd i'll happily look into this for you!

I've only used Jessie, tested wheezy to see if it boots didn't check the disk used. It's the weekend and will start fixing monday.

Have a great sunday! :+1:
